services:
  db:
    image: postgres:alpine3.19
    ports:
      - "5469:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s