# Test your FastAPI endpoints

GET http://127.0.0.1:8069/cars
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmRfdmVyc2lvbiI6MTQ3NDIwNTQ3OCwiZXhwaXJ5IjoxNzE1MTYwMzM4LjE1ODI5NH0.s2t7liLGviNQxfmbsuJAEMpCG1gMVAavVFv4YN1xz94
Accept: application/json

###

GET http://127.0.0.1:8069/cars/55
Accept: application/json

###

POST http://127.0.0.1:8069/cars
Accept: application/json
Content-Type: application/json

{
  "registration_id": "55",
  "make": "Ferrari",
  "model": "SF-24",
  "year": 2024,
  "color": "red",
  "owner": "Carlos Sainz"
}

###

PATCH http://127.0.0.1:8069/cars
Accept: application/json
Content-Type: application/json

{
  "registration_id": "55",
  "owner": "Lewis Hamilton",
  "model": "SF-25",
  "year": 2025,
  "color": "red"
}

###

PATCH http://127.0.0.1:8069/cars
Accept: application/json
Content-Type: application/json

{
  "registration_id": "55",
  "password": "F*** Carlos"
}

###

DELETE http://127.0.0.1:8069/cars/55
Accept: application/json

###

GET http://127.0.0.1:8069/admin/password-set
Accept: application/json

###

POST http://127.0.0.1:8069/admin/login
Accept: application/json
Content-Type: application/json

{
  "password": "password"
}

###

POST http://127.0.0.1:8069/admin/change-password
Accept: application/json
Content-Type: application/json

{
  "new_password": "password"
}
